brew install alfred
brew install 1password
brew install 1password-cli
brew install keyboard-cleaner
brew install spectacle
brew install iterm2
brew install visual-studio-code
brew install whatsapp
brew install vlc
brew install itsycal
brew install google-chrome
brew install google-chrome-canary
brew install google-backup-and-sync
brew install licecap
brew install telegram
brew install android-file-transfer
brew install spotify
brew install meetingbar
brew install thefuck

brew cleanup -s
